config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    Rails.application.routes.draw do
      root to: 'pages#show', id: 'talents'
      devise_for :users, controllers: {registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       confirmations: 'confirmations'}
      # get 'high_voltage/pages', to: 'high_voltage#pages'
      get '/pages/*id' => 'pages#show'
      get '/companies/:company_id/posts/:id', to: 'user_logged/posts#show', as: 'post'
      resources :after_signups, only: [:index]
      resources :subscriptions, only: %i[new create]
      get '/subscriptions/edit', to: 'subscriptions#edit', as: 'edit_subscription'
      get '/subscriptions/confirm', to: 'subscriptions#confirm', as: 'confirm_subscription_upgrade'
      put '/subscriptions/upgrade', to: 'subscriptions#update', as: 'update_subscription'
      resources :stripe_hooks, only: [:create]
      resources :mandrill_hooks, only: [:create]
      resources :partner_requests, only: [:create]
      resource :resend_confirmations, only: %i[new create]
      resources :tell_friends, only: [:create]
      resources :solutions, only: [:index]
      resources :company_searches, only: [:index]
      get '/create_company_searches', to: 'company_searches#create', as: 'get_create_company_searches'
      post '/create_company_searches', to: 'company_searches#create', as: 'post_create_company_searches'
      namespace :user_logged do
        get '/company_admins/:id', to: 'company_admins#create', as: 'become_admin'
        resources :company_nationalities, only: [:create, :update, :destroy]
        resources :company_languages, only: [:create, :update, :destroy]
        resources :company_profiles, only: [:update]
        resources :company_data, only: [:update]
        resource :companies, only: %i[new create edit update]
        resources :companies, only: [:show]
        resources :company_informations, only: [:update]
        resources :company_information_requests, only: [:create]
        resources :companies_diversity_policies, only: %i[create destroy]
        resources :text_policies, only: %i[create destroy]
        resources :goals_ways, only: %i[create destroy]
        resources :charges, only: %i[new create]
        resource :account_settings, only: %i[show edit update]
        resources :policy_requests, only: [:create]
        resources :policy_request_fields, only: [:create]
        resources :goal_requests, only: [:create]
        resources :diversity_requests, only: [:create]
        resources :company_requests, only: [:create]
        resources :coupons, only: [:create]
        resources :comments, only: %i[create destroy]
        resources :likes, only: [:create]
        resources :posts, only: %i[create update destroy]
        resources :follows, only: [:create]
        resource :walls, only: [:show]
        namespace :solutions do
          resource :axiom, only: [:show]
          resource :ontheagenda, only: [:show]
          resource :inspired_beyond_babies, only: [:show]
          resource :potential_company, only: [:show]
          resource :engaged_leadership, only: [:show]
          resource :introdus, only: [:show]
        end
        resources :solution_requests, only: [:create]
        namespace :account_settings do
          resources :billings, only: [:index]
          resources :upcoming_payments, only: [:index]
          resources :plans_users, only: %i[index destroy]
          resources :admin_invites, only: %i[index update]
          resources :notifications, only: %i[index update]
          resources :payment_credentials, only: [:edit, :new, :update, :create]
        end
        resource :company_settings, only: %i[show edit update]
        namespace :company_settings do
          resources :admins, only: %i[index update destroy]
          resources :admin_invites, only: %i[create update]
          resources :admin_requests, only: %i[update destroy]
          resources :info_requests, only: [:index]
          resources :diversity_requests, only: [:index]
          resources :goal_requests, only: [:index]
          resources :policy_requests, only: [:index]
          resources :followers_stats, only: [:index]
        end
        resource :platform_settings, only: [:show, :update]
        namespace :platform_settings do
          resources :users, only: %i[index show update destroy]
          resources :companies
          resources :requests, only: [:index]
          resources :plans, only: %i[index edit update]
          resources :employees_counts, except: [:show]
          resources :industries, except: [:show]
          resources :company_information_requests, only: [:index]
          resources :diversity_requests, only: [:index]
          resources :goal_requests, only: [:index]
          resources :policy_requests, only: [:index]
          resources :request_companies, only: [:create]
          resources :nationalities, except: [:show]
          resources :languages, except: [:show]
          resource :user_exports, only: [:show]
        end
      end
    end
  end
end

app/controllers/user_logged/account_settings/admin_invites_controller.rb
# frozen_string_literal: true

module UserLogged
  module AccountSettings
    class AdminInvitesController < BaseController
      layout 'mixed'
      def index
        @admin_invites = AdminInvite.for_user(current_user).ordered.decorate
      end

      def update
        result = ::Command::AccountSettings::AdminInvites::Update.new(params, current_user).call
        update_respond(result)
      end

      private

      def update_respond(result)
        respond(result,
                user_logged_account_settings_admin_invites_path,
                user_logged_account_settings_admin_invites_path)
      end
    end
  end
end

app/controllers/user_logged/account_settings/billings_controller.rb
# frozen_string_literal: true

module UserLogged
  module AccountSettings
    class BillingsController < BaseController
      layout 'mixed'
      def index
        @billings = current_user.billings.order(updated_at: :desc).decorate
      end
    end
  end
end

app/controllers/user_logged/account_settings/payment_credentials_controller.rb
# frozen_string_literal: true

module UserLogged
  module AccountSettings
    class PaymentCredentialsController < BaseController
      layout 'mixed'

      def new
        redirect_to root_path if current_user.stripe_customer_id.blank?
      end

      # Changes made by James Wilson without applying Rubocop rules
      # rubocop:disable all
      def create
        if current_user.stripe_customer_id.present?
          begin
            customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
            card = customer.sources.create(source: params[:stripeToken])
            card.save
            customer.default_source = card.id
            if customer.save
              if current_user.payment_credential.present?
                current_user.payment_credential.update_attributes!(
                  last4: card.last4, exp_month: card.exp_month,
                  exp_year: card.exp_year, card_type: card.brand
                )
                flash[:success] = 'Card updated successfully'
                redirect_to new_user_logged_account_settings_payment_credential_path
              else
                params[:card_type] = card.brand
                params[:last4] = card.last4
                params[:stripe_customer_id] = current_user.stripe_customer_id
                params[:user_id] = current_user.id
                form = ::Form::UserLogged::AccountSettings::PaymentCredentials::New.new(create_params)
                respond(::Command::PaymentCredentials::Create.new(form).call,
                        new_user_logged_account_settings_payment_credential_path,
                        new_user_logged_account_settings_payment_credential_path)
              end
            else
              flash[:error] = 'Stripe reported an error while updating your card. Please try again.'
            end
          rescue StandardError => e
            flash[:error] = 'Stripe reported an error while updating your card. Please try again.'
            redirect_to new_user_logged_account_settings_payment_credential_path
          end
        else
          flash[:error] = 'Stripe reported an error while updating your card. Please try again.'
        end
      end
      # rubocop:enabledisable all

      def edit; end

      def update; end

      private

      def create_params
        params.permit(:last4, :exp_month, :stripe_customer_id, :user_id, :exp_year, :card_type)
      end
    end
  end
end

app/controllers/user_logged/account_settings/plans_users_controller.rb
# frozen_string_literal: true

module UserLogged
  module AccountSettings
    class PlansUsersController < BaseController
      layout 'mixed'
      def index
        @plans_users = current_user
                       .plans_users
                       .includes(:plan)
                       .includes(:billing)
                       .order(updated_at: :desc)
                       .decorate
      end

      def destroy
        # XXX: check if owner
        result = ::Command::UserPlan::Cancel.new(current_user, params[:id]).call
        if result.success?
          redirect_to user_logged_account_settings_plans_users_path, notice: result.data
        else
          redirect_to root_path, alert: result.error.message
        end
      end
    end
  end
end

app/controllers/user_logged/account_settings/upcoming_payments_controller.rb
# frozen_string_literal: true

module UserLogged
  module AccountSettings
    class UpcomingPaymentsController < BaseController
      layout 'mixed'
      def index
        result = ::Query::Billing::FindUpcoming.new(current_user).call
        if result.success?
          @upcoming_payment = result.data
        else
          respond_error(result.error, user_logged_account_settings_path)
        end
      end
    end
  end
end

app/controllers/user_logged/account_settings_controller.rb
# frozen_string_literal: true

module UserLogged
  class AccountSettingsController < BaseController
    layout 'mixed'
    def show
      redirect_to edit_user_logged_account_settings_path
    end

    def edit
      @user = ::Form::UserLogged::AccountSettings::Edit.find(current_user)
    end

    def update
      @user = ::Form::UserLogged::AccountSettings::Edit.find(current_user)
      @user.attributes = update_user_params
      result = ::Command::AccountSettings::Update.new(current_user, @user).call
      if result.success?
        respond_success(result.data, edit_user_logged_account_settings_path)
      else
        flash[:error] = 'Invalid data in form prohibited it from saving!'
        render :edit
      end
    end

    private

    def update_user_params
      params.require(:user).permit(:avatar,
                                   :remove_avatar,
                                   :name,
                                   :surname,
                                   :email,
                                   :company_name,
                                   :title,
                                   :company_representative,
                                   :newsletter_subscription)
    end
  end
end

app/controllers/user_logged/base_controller.rb
# frozen_string_literal: true

module UserLogged
  class BaseController < ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/user_logged/base_platform_controller.rb
# frozen_string_literal: true

module UserLogged
  class BasePlatformController < BaseController
    before_action :check_if_admin

    private

    def check_if_admin
      redirect_to root_path, flash: {error: 'Access denied!'} unless policy(:users).platform_admin?
    end
  end
end

app/controllers/user_logged/charges_controller.rb
# frozen_string_literal: true

module UserLogged
  class ChargesController < BaseController
    before_action :find_billing

    def new
      # if current_user.pro?
      #   redirect_to new_subscription_path,
      #               error: 'You already have an active subscription.'
      # end
      # write user_id if billing was started before singup/signin
      @billing.user_id = current_user.id unless @billing.user_id
      @billing.save!
      @plan = ::PlanDecorator.decorate(@billing.plan)
      @become_admin_company_id = params[:company_id]
    end

    def create
      @plan_name = ::PlanDecorator.decorate(@billing.plan).name
      result = charge_payment
      become_admin_form
      raise result.error unless result.success?
    rescue Stripe::CardError => e
      redirect_to new_user_logged_charge_path, alert: e.message
    rescue StandardError => e
      redirect_to root_path, alert: e.message
    end

    private

    def become_admin_form
      @become_admin_form = ::Form::Company::BecomeAdmin.new
      @company_id = params[:become_admin_company_id]
    end

    def charge_payment
      ::Command::Charge::Payment.new(current_user, session, params).call
    end

    def find_billing
      @billing = begin
                   Billing.find(session[:current_billing_id]).decorate
                 rescue StandardError
                   nil
                 end
    end
  end
end

app/controllers/user_logged/comments_controller.rb
# frozen_string_literal: true

module UserLogged
  class CommentsController < BaseController
    def create
      @form = ::Form::UserLogged::Comment::New.new(create_params.merge(created_by: current_user.id))
      result = ::Command::Comment::Create.new(@form).call
      respond(result)
    end

    def destroy
      @comment = Comment.find(params[:id])
      authorize @comment, :can_destroy?
      result = ::Command::Comment::Destroy.new(@comment).call
      respond(result)
    end

    private

    def create_params
      params.require(:comment).permit(:text, :post_id)
    end

    def respond(result)
      route = begin
                user_logged_company_path(Post.find(params[:comment][:post_id]).company.id)
              rescue StandardError
                user_logged_company_path(@comment.post.company_id)
              end
      super(result, route, route)
    end

    def respond_success(message, path)
      respond_to do |format|
        format.json do
          post = begin
                   Post.find(@form.post_id)
                 rescue StandardError
                   Post.find(@comment.post_id)
                 end
          render status: :ok, html: render_to_string(
            'user_logged/posts/_comments.html', locals: {post: post}, layout: false
          )
        end
        format.html { redirect_to path, notice: message }
      end
    end
  end
end

app/controllers/user_logged/companies_diversity_policies_controller.rb
# frozen_string_literal: true

module UserLogged
  class CompaniesDiversityPoliciesController < ::UserLogged::CompaniesController
    def create
      @company = Company.find(params[:companies_diversity_policies][:company_id])
      authorize @company, :company_admin?
      form = ::Form::UserLogged::CompaniesDiversityPolicy::New.new(create_params)
      respond(::Command::CompaniesDiversityPolicy::Create.new(form).call)
    end

    def destroy
      companies_diversity_policy = CompaniesDiversityPolicy.find(params[:id])
      @company = companies_diversity_policy.company
      authorize @company, :company_admin?
      companies_diversity_policy.destroy
      respond_success('Deleted successfully.')
    end

    private

    def create_params
      params.require(:companies_diversity_policies).permit(:diversity_policy_id, :company_id)
    end
  end
end

app/controllers/user_logged/company_admins_controller.rb
# frozen_string_literal: true

module UserLogged
  class CompanyAdminsController < BaseController
    def create
      form = ::Form::Company::BecomeAdmin.new(become_admin_params)
      result = ::Command::Company::BecomeAdmin.new(current_user, form, params[:id]).call
      respond(result)
    end

    private

    def become_admin_params
      params.require(:form_company_become_admin).permit(:acceptance)
    end

    def success_respond_path
      user_has_name = current_user.name.present? && current_user.surname.present?
      user_has_name ? user_logged_company_path(params[:id]) : edit_user_logged_account_settings_path
    end

    def failure_respond_path
      current_user.company_id? ? success_respond_path : user_logged_company_path(params[:id])
    end

    def respond(result)
      super(result, success_respond_path, failure_respond_path)
    end
  end
end

app/controllers/user_logged/company_data_controller.rb
# frozen_string_literal: true

module UserLogged
  class CompanyDataController < ::UserLogged::CompaniesController
    def update
      @company = Company.find(params[:id])
      authorize @company, :company_admin_with_paid_plan?
      form = ::Form::UserLogged::CompanyData::Edit.find(@company.id)
      form.attributes = update_params
      respond(
        ::Command::CompanyData::Update.new(
          form,
          ::UsersPolicy.new(current_user, current_user).platform_admin?
        ).call
      )
    end

    private

    def update_params
      params.require(:company_profile).permit(
        :employees_count_id,
        :liabilities,
        :revenue
      )
    end
  end
end

app/views/user_logged/walls/_company_stats.html.slim
- company_profile = company.company_profile.decorate
.card.rounded.border-0.text-center.company_tile.show-followed-list class=[('hidden' if company_counter > 2)]
  a.card-block.clearfix.p-3 href='#{user_logged_company_path(company)}'
    .card-subtitle
      = company.name
    .paragraph-small title="#{company.industry&.name}"
      = truncate(company.industry.name, length: 16) rescue "&nbsp;".html_safe
    .company_info-featured
      .card-img-top
        .score-graph.score-graph--tile.mx-auto.mb-3
          = inline_svg('score_graph_featured-company.svg', data: {score: company_profile.total_diversity_score})
          .score-graph__value-wrapper.company-tile-svg
            .score-graph__logo
              = company.logo_extra_small
      .company_info-values.mt-2
        .card-title.mx-3
          .paragraph-small 
            .label.label-scores Scores:
            | Gender
          h6 = number_to_percentage(company_profile.total_diversity_score, precision: 0) || '0%'
        .card-title
          .paragraph-small Ethnicity
          .label.label-extra-small 
            span.span-value = company.languages_count 
            span  Languages
          .label.label-extra-small 
            span.span-value = company.nationalities_count 
            span  Nationalities
  - if company.posted_recently?
    .recently-posts
      .label.label-scores New activity:
      .recently-flex
        span.fa.fa-comment-o 
        .paragraph-small Posted recently
  .company_info-actions.pb-3.horizontal-border.horizontal-border-top
    div.show-profile
      = link_to 'Show profile', user_logged_company_path(company), class: 'btn btn-link'
      i.fa.fa-arrow-right

app/views/user_logged/walls/_company_tile_wall.slim
- company_profile = company.company_profile.decorate
.card.rounded.border-0.text-center.company_tile
  a.card-block.clearfix.p-3 href='#{user_logged_company_path(company)}'
    .card-subtitle
      = company.name
    .paragraph-small title="#{company.industry&.name}"
      = truncate(company.industry.name, length: 16) rescue "&nbsp;".html_safe
    .company_info-featured
      .card-img-top
        .score-graph.score-graph--tile.mx-auto.mb-3
          = inline_svg('score_graph_featured-company.svg', data: {score: company_profile.total_diversity_score})
          .score-graph__value-wrapper.company-tile-svg
            .score-graph__logo
              = company.logo_extra_small
      .company_info-values
        .card-title.mx-3
          .paragraph-small 
            .label.label-scores Scores:
            | Gender
          h6 = number_to_percentage(company_profile.total_diversity_score, precision: 0) || '0%'
        .card-title
          .paragraph-small Ethnicity
          .label.label-extra-small 
            span.span-value = company.languages_count 
            span  Languages 
          .label.label-extra-small 
            span.span-value = company.nationalities_count 
            span  Nationalities 
  .company_info-actions.pb-3.horizontal-border.horizontal-border-top
    div.learn-more
      = link_to 'Display profile', user_logged_company_path(company), class: 'btn btn-link'
      i.fa.fa-arrow-right
    = follow_helper(company, current_user)
    

app/views/user_logged/walls/_show_companies.html.slim
.container
  .row.pt-2.no-gutters
    .col-lg-3.hidden-md-down
      .card.card-border
        h6.p-3.horizontal-border Featured companies
        = render(partial: 'company_tile_wall',
                  collection: @featured.first(3),
                  as: :company) || '<div class="p-3"> No companies found. </div>'.html_safe
      .center-btn
        button.btn.btn-primary.btn-square.my-4 = link_to 'BROWSE ALL COMPANIES', company_searches_path
    == render 'show_stream'
    .col-12.hidden-lg-up
      .card.card-border
        h6.p-3.horizontal-border Featured companies
        = render(partial: 'company_tile_wall',
                  collection: @featured.first(3),
                  as: :company) || '<div class="p-3"> No companies found. </div>'.html_safe
      .center-btn
        button.btn.btn-primary.btn-square.my-4 = link_to 'BROWSE ALL COMPANIES', company_searches_path
    .col-lg-3
      .card.card-border.mb-4
        h6.p-3.horizontal-border Companies you follow
        = render(partial: 'company_stats',
                collection: @followed,
                as: :company) || '<div class="p-3"> No companies found. </div>'.html_safe
      .center-btn#show-list-btn
        button.btn.btn-primary.my-4.btn-square#show-full-list SHOW FULL LIST  

app/views/user_logged/walls/_show_search.html.slim
.card.wall__container_search
  .container.py-4.px-3
    = simple_form_for @company_search_simple, url: post_create_company_searches_path, html: {class: 'form-inline'}, method: :post do |f|
      = f.input :name, label: false,  wrapper: :vertical_input_group, wrapper_html: {class: 'w-100'}
        = f.input_field :name, class: 'form-control w-400px form-control--dark form-control--bright', placeholder: 'Search company...'
        .input-group-btn
          = f.button :button, class: 'button btn btn-primary btn--circle btn--dark btn--bright' do
            i.fa.fa-search
    .text-center
      p.white.pt-4= link_to 'See all companies featured on GoGetty', company_searches_path

app/views/user_logged/walls/_show_stream.html.slim
.col-lg-6
  .mx-3.mb-4
      == render partial: 'user_logged/posts/post', collection: @gogetty_posts
      == render partial: 'user_logged/posts/post', collection: @posts
      == paginate @posts

app/views/user_logged/walls/_show_summary.html.slim
.card.pb-4.pt-3.mb-3.wall-header
  .container
    .row.align-items-end.no-gutters
      .col-lg-9 
        .paragraph.pb-2 Welcome back to GoGetty.co
        h1 Latest news and articles
      .col-lg-3
        .my-3
          = current_user.decorate.avatar
        .text-center
        .paragraph.paragarph-user-details = current_user.full_name
        .label= current_user.decorate.company_title

app/views/user_logged/walls/show.html.slim
.wall
  == render 'show_summary'
  == render 'show_companies'