config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    Rails.application.routes.draw do
      root to: 'pages#show', id: 'talents'
      devise_for :users, controllers: {registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       confirmations: 'confirmations'}
      # get 'high_voltage/pages', to: 'high_voltage#pages'
      get '/pages/*id' => 'pages#show'
      get '/companies/:company_id/posts/:id', to: 'user_logged/posts#show', as: 'post'
      resources :after_signups, only: [:index]
      resources :subscriptions, only: %i[new create]
      get '/subscriptions/edit', to: 'subscriptions#edit', as: 'edit_subscription'
      get '/subscriptions/confirm', to: 'subscriptions#confirm', as: 'confirm_subscription_upgrade'
      put '/subscriptions/upgrade', to: 'subscriptions#update', as: 'update_subscription'
      resources :stripe_hooks, only: [:create]
      resources :mandrill_hooks, only: [:create]
      resources :partner_requests, only: [:create]
      resource :resend_confirmations, only: %i[new create]
      resources :tell_friends, only: [:create]
      resources :solutions, only: [:index]
      resources :company_searches, only: [:index]
      get '/create_company_searches', to: 'company_searches#create', as: 'get_create_company_searches'
      post '/create_company_searches', to: 'company_searches#create', as: 'post_create_company_searches'
      namespace :user_logged do
        get '/company_admins/:id', to: 'company_admins#create', as: 'become_admin'
        resources :company_nationalities, only: [:create, :update, :destroy]
        resources :company_languages, only: [:create, :update, :destroy]
        resources :company_profiles, only: [:update]
        resources :company_data, only: [:update]
        resource :companies, only: %i[new create edit update]
        resources :companies, only: [:show]
        resources :company_informations, only: [:update]
        resources :company_information_requests, only: [:create]
        resources :companies_diversity_policies, only: %i[create destroy]
        resources :text_policies, only: %i[create destroy]
        resources :goals_ways, only: %i[create destroy]
        resources :charges, only: %i[new create]
        resource :account_settings, only: %i[show edit update]
        resources :policy_requests, only: [:create]
        resources :policy_request_fields, only: [:create]
        resources :goal_requests, only: [:create]
        resources :diversity_requests, only: [:create]
        resources :company_requests, only: [:create]
        resources :coupons, only: [:create]
        resources :comments, only: %i[create destroy]
        resources :likes, only: [:create]
        resources :posts, only: %i[create update destroy]
        resources :follows, only: [:create]
        resource :walls, only: [:show]
        namespace :solutions do
          resource :axiom, only: [:show]
          resource :ontheagenda, only: [:show]
          resource :inspired_beyond_babies, only: [:show]
          resource :potential_company, only: [:show]
          resource :engaged_leadership, only: [:show]
          resource :introdus, only: [:show]
        end
        resources :solution_requests, only: [:create]
        namespace :account_settings do
          resources :billings, only: [:index]
          resources :upcoming_payments, only: [:index]
          resources :plans_users, only: %i[index destroy]
          resources :admin_invites, only: %i[index update]
          resources :notifications, only: %i[index update]
          resources :payment_credentials, only: [:edit, :new, :update, :create]
        end
        resource :company_settings, only: %i[show edit update]
        namespace :company_settings do
          resources :admins, only: %i[index update destroy]
          resources :admin_invites, only: %i[create update]
          resources :admin_requests, only: %i[update destroy]
          resources :info_requests, only: [:index]
          resources :diversity_requests, only: [:index]
          resources :goal_requests, only: [:index]
          resources :policy_requests, only: [:index]
          resources :followers_stats, only: [:index]
        end
        resource :platform_settings, only: [:show, :update]
        namespace :platform_settings do
          resources :users, only: %i[index show update destroy]
          resources :companies
          resources :requests, only: [:index]
          resources :plans, only: %i[index edit update]
          resources :employees_counts, except: [:show]
          resources :industries, except: [:show]
          resources :company_information_requests, only: [:index]
          resources :diversity_requests, only: [:index]
          resources :goal_requests, only: [:index]
          resources :policy_requests, only: [:index]
          resources :request_companies, only: [:create]
          resources :nationalities, except: [:show]
          resources :languages, except: [:show]
          resource :user_exports, only: [:show]
        end
      end
    end
  end
end

app/controllers/solutions_controller.rb
# frozen_string_literal: true

class SolutionsController < ApplicationController
  layout 'static'

  def index; end
end

app/controllers/user_logged/solutions/axioms_controller.rb
# frozen_string_literal: true

module UserLogged
  module Solutions
    class AxiomsController < UserLogged::SolutionsController; end
  end
end

app/controllers/user_logged/solutions/engaged_leaderships_controller.rb
# frozen_string_literal: true

module UserLogged
  module Solutions
    class EngagedLeadershipsController < UserLogged::SolutionsController; end
  end
end

app/controllers/user_logged/solutions/inspired_beyond_babies_controller.rb
# frozen_string_literal: true

module UserLogged
  module Solutions
    class InspiredBeyondBabiesController < UserLogged::SolutionsController; end
  end
end

app/controllers/user_logged/solutions/introdus_controller.rb
# frozen_string_literal: true

module UserLogged
  module Solutions
    class IntrodusController < UserLogged::SolutionsController; end
  end
end

app/controllers/user_logged/solutions/ontheagendas_controller.rb
# frozen_string_literal: true

module UserLogged
  module Solutions
    class OntheagendasController < UserLogged::SolutionsController; end
  end
end

app/controllers/user_logged/solutions/potential_companies_controller.rb
# frozen_string_literal: true

module UserLogged
  module Solutions
    class PotentialCompaniesController < UserLogged::SolutionsController; end
  end
end

app/controllers/user_logged/solutions_controller.rb
# frozen_string_literal: true

module UserLogged
  class SolutionsController < BaseController
    layout 'static'

    def show; end
  end
end

app/views/pages/solutions/_for_companies_card.html.slim
= link_to  page_path('solutions/companies')
  .solutions-card.py-5.my-2
    = image_tag 'for-companies.svg', class: 'my-4'
    h4 For companies
    .paragraph Join GoGetty as a Company and grow your revenue
  

app/views/pages/solutions/_for_partners_card.html.slim
= link_to  page_path('solutions/partners')
  .solutions-card.py-5.my-2
    = image_tag 'for-solution-partners.svg', class: 'my-4'
    h4 For solution partners
    .paragraph Become the preferred diversity and inclusion Solution Partner

app/views/pages/solutions/_for_talents_card.html.slim
= link_to  page_path('solutions/talents')
  .solutions-card.py-5.my-2
    = image_tag 'for-talents.svg', class: 'my-4'
    h4 For talents
    .paragraph Use GoGetty to create meaningful carrier

app/views/pages/solutions/_menu.html.slim
.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_axiom.png', size:'51x32')
  div.float-none
    h4= link_to 'Axiom', '#company-1', class: 'animateScroll'

.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_ontheagenda.png', size: '80x26')
  div.float-none
    h4= link_to 'On The Agenda', '#company-2', class: 'animateScroll'

.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_ibb.svg', size: '51x23')
  div.float-none
    h4= link_to 'Inspired Beyond Babies', '#company-3', class: 'animateScroll'

.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_potential.png', size: '49x9')
  div.float-none
    h4= link_to 'Potential Company', '#company-4', class: 'animateScroll'

.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_engaged.png', size: '50x35')
  div.float-none
    h4= link_to 'Engaged Leadership', '#company-5', class: 'animateScroll'

.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_introdus.png', size: '45x30')
  div.float-none
    h4= link_to 'introDus', '#company-6', class: 'animateScroll'

.solutions__menu_content.solutions__menu_content--selected.solutions__menu_content--whole_link
  div.float-right
    = image_tag('logos/logo_girls.png', size: '60x40')
  div.float-none
    h4= link_to 'Girls are Awesome', '#company-7', class: 'animateScroll'

app/views/pages/solutions/_more_info.slim
#solutions_more_info.modal.fade aria-hidden="true" aria-labelledby="solutions_more_info_label" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .text-right.py-2.px-3
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true" &times;
      .modal-header
        .text-center
          .modal-title-image.py-3=image_tag('icons/modal_solution_1.svg')
          #how_this_works_add_company_label.modal-title.px-5 Please confirm Your request
      .modal-body.px-5
        | And take an important step towards more diversity and inclusion. The GoGetty Team will put you in contact with 
        span id="solutions_more_info__company"
        | .
      .modal-footer
        = simple_form_for :solution_request, url: user_logged_solution_requests_path do |f|
          = f.input :name, as: :hidden
          = f.input :company, as: :hidden
          = f.hidden_field :back_url, value: request.path
          = f.button :submit, 'Confirm', class: "btn btn-secondary", id: 'proceed'

app/views/pages/solutions/_partner_request.html.slim
#partner_request.modal.fade aria-hidden="true" aria-labelledby="partner_request_label" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .text-right.py-2.px-3
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true" &times;
      .modal-header
        .text-center
          .modal-title-image.py-3=image_tag('icons/modal_solution_1.svg')
          add_company_label.modal-title Let us contact You
      = simple_form_for :partner_request, url: partner_requests_path do |f|
        .modal-body.px-5
          .mb-4 Our staff will contact You to consult all required details for the offer

          = f.input :name,
            label: false,
            placeholder: 'Name',
            input_html: {value: current_user&.name}

          = f.input :surname,
            label: false,
            placeholder: 'Surname',
            input_html: {value: current_user&.surname}

          = f.input :email,
            label: false,
            placeholder: 'Email',
            input_html: {value: current_user&.email}

          = f.input :company_name,
            label: false,
            placeholder: 'Company name',
            input_html: {value: current_user&.company_name}

          = f.input :product, as: :text,
            label: false,
            placeholder: 'Short description of your D&I service'

        .modal-footer
          = f.button :submit, 'Confirm', class: 'button btn btn-secondary', id: 'proceed'

app/views/pages/solutions/_solutions_content.html.slim
== render 'pages/solutions/partner_request'
.container
  .row
    .col
      h1.my-4 Our Solution Partners
.container.solutions
  .row
    .col-12.col-lg-4.push-lg-8.solutions__menu
      .solutions__menu_header
        h6 Currently provided services:
      .solutions__menu--sticky
        == render 'pages/solutions/menu'
    .col-12.col-lg-8.pull-lg-4.solutions__content
      / TODO: transform this into loop after transfering offers to DB
      .row
        .col-lg-6 
          .solution-card
            == render 'pages/solutions/axiom/partner'
        .col-lg-6
          .solution-card
            == render 'pages/solutions/ontheagenda/partner'
        .col-lg-6
          .solution-card
            == render 'pages/solutions/inspired_beyond_babies/partner'
        .col-lg-6
          .solution-card
            == render 'pages/solutions/engaged_leadership/partner'
        .col-lg-6
         .solution-card
            == render 'pages/solutions/introdus/partner'
        .col-lg-6
          .solution-card
            == render 'pages/solutions/girls/partner'

app/views/pages/solutions/companies.html.slim
.solutions-page
  nav.navbar.navbar-light.bg-light.flex-display-row
    = link_to 'For companies', page_path('solutions/companies'), class: 'navbar-brand navbar-brand-active'
    = link_to 'For talents', page_path('solutions/talents'), class: 'navbar-brand'
    = link_to 'For solution partners', page_path('solutions/partners'), class: 'navbar-brand'
  .solutions-header.solutions-companies
    .header-content
      h1 Join GoGetty as a Company and grow your revenue
      .paragraph.my-5.paragraph-gray Diversity means better financial results, more innovative ideas, more satisfied customers and employees, who stay longer.
      = link_to 'TAKE OVER YOUR PROFILE ON GOGETTY', new_user_registration_path, class: 'btn btn-default btn-block btn-transparent'
  .solutions-content
    .container
      .row
        .col-lg-1
        .col-lg-10
          .container
            .row.py-5.my-4
              .col-lg-6
                .mobile-center
                  = image_tag 'for-companies.svg', class: 'my-4'
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Share your company’s diversity facts
                  .paragraph.mt-3
                    | GoGetty makes gender and soon also other diversity parameters in Top Management in Denmark visible and hence measurable.
                    <br>
                    | Be 100% transparent on your diversity journey
            .row.py-5.my-4
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Benchmark Your gender statistics
                  .paragraph.mt-3
                    | Compare and benchmark your diversity numbers with other companies in Denmark.
                    <br>
                    | Find out where you stand, learn from the best and continue to improve.
              .col-lg-6
                .flex-display-img
                  = image_tag 'AB.svg', class: 'my-4'
            .row.py-5.my-4
              .col-lg-6
                .mobile-center
                  = image_tag 'arrow.svg', class: 'my-4'
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Take informed decisions
                  .paragraph.mt-3
                    | GoGetty enables ambitious and highly qualified talents as well as companies to find each other. 
                    <br>
                    | Use your diversity facts as part of your Company’s employer brand.
            .row.py-5.my-4
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Grow your revenue
                  .paragraph.mt-3
                    | Fully reap the benefits of a diverse workforce and tap into a rich pool of diverse talents. Attract and retain them!
              .col-lg-6
                .flex-display-img
                  = image_tag 'increased-charts.svg', class: 'my-4'
        .solutions-footer
          .container
            .row
              .col-lg-6
                == render "pages/solutions/for_talents_card"
              .col-lg-6
                == render "pages/solutions/for_partners_card"
        .col-lg-1
    == render "pages/solutions/solutions_content" 
    == render 'pages/solutions/more_info'

app/views/pages/solutions/partners.html.slim
= render 'pages/solutions/partner_request' 
.solutions-page
  nav.navbar.navbar-light.bg-light.flex-display-row
    = link_to 'For companies', page_path('solutions/companies'), class: 'navbar-brand'
    = link_to 'For talents', page_path('solutions/talents'), class: 'navbar-brand'
    = link_to 'For solution partners', page_path('solutions/partners'), class: 'navbar-brand navbar-brand-active'
  .solutions-header.solutions-partners
    .header-content
      h1 Become the preferred diversity and inclusion Solution Partner
      .paragraph.my-5.paragraph-gray Diversity means better financial results, more innovative ideas, more satisfied customers and employees, who stay longer.
      = link_to 'BECOME GOGETTY SOLUTION PARTNER', '#', data: {target: '#partner_request', toggle: 'modal'}, class: 'btn btn-default btn-block btn-transparent'
  .solutions-content
    .container
      .row
        .col-lg-1
        .col-lg-10
          .container
            .row.py-5.my-4
              .col-lg-6
                .mobile-center
                  = image_tag 'keyboard-hands.svg', class: 'my-4'
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Offer your D&I services on the GoGetty diversity platform
                  .paragraph.mt-3
                    | As many of 2,000 Danish companies can today become your customers. Become their preferred solution partner and offer your services
            .row.py-5.my-4
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Easily find companies who need your help
                  .paragraph.mt-3
                    | GoGetty makes diversity in management visible and hence measurable. Compare diversity numbers, goals and policies between different companies of your interest. Find out where they stand and offer your services, where you can help.
              .col-lg-6
                .flex-display-img
                  = image_tag 'group.svg', class: 'my-4'
            .row.py-5.my-4
              .col-lg-6
                .mobile-center
                  = image_tag 'garland.svg', class: 'my-4'
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Learn from what other D&I Solution Partners are offering
                  .paragraph.mt-3
                    | Find out where you stand, learn from the best and continue to improve. And contribute to the community with your knowledge within the field of diversity and inclusion.
            .row.py-5.my-4
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Grow your D&I service offering and your business
                  .paragraph.mt-3
                    | The market for diversity and inclusion is expanding rapidly. On GoGetty, you can find your next customer and grow your business.
              .col-lg-6
                .flex-display-img
                  = image_tag 'balance-people.svg', class: 'my-4'
        .solutions-footer
          .container
            .row
              .col-lg-6
                == render "pages/solutions/for_talents_card"
              .col-lg-6
                == render "pages/solutions/for_companies_card"
        .col-lg-1
    == render "pages/solutions/solutions_content" 
    == render 'pages/solutions/more_info'

app/views/pages/solutions/talents.html.slim
.solutions-page
  nav.navbar.navbar-light.bg-light.flex-display-row
    = link_to 'For companies', page_path('solutions/companies'), class: 'navbar-brand'
    = link_to 'For talents', page_path('solutions/talents'), class: 'navbar-brand navbar-brand-active'
    = link_to 'For solution partners', page_path('solutions/partners'), class: 'navbar-brand'
  .solutions-header.solutions-talents
    .header-content
      h1 Use GoGetty to create a meaningful career
      .paragraph.my-5.paragraph-gray Diversity means better financial results, more innovative ideas, more satisfied customers and employees, who stay longer.
      = link_to 'BECOME GOGETTY TALENT', new_user_registration_path, class: 'btn btn-default btn-block btn-transparent'
  .solutions-content
    .container
      .row
        .col-lg-1
        .col-lg-10
          .container
            .row.py-5.my-4
              .col-lg-6
                .mobile-center
                  = image_tag 'for-companies.svg', class: 'my-4'
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Find out which companies can help you reach all the way to the top
                  .paragraph.mt-3
                    | GoGetty makes diversity in management visible and hence measurable. Our first goal is to accelerate the process of more women, like yourself, reaching top management positions.
            .row.py-5.my-4
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Compare diversity numbers, goals and policies between different companies of your interest.
                  .paragraph.mt-3
                    | Compare diversity numbers, goals and policies between different companies of your interest. Find out where they stand and follow their development towards more diverse and inclusive management.
              .col-lg-6
                .flex-display-img
                  = image_tag 'AB.svg', class: 'my-4'
            .row.py-5.my-4
              .col-lg-6
                .mobile-center
                  = image_tag 'arrow.svg', class: 'my-4'
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Take informed decisions
                  .paragraph.mt-3
                    | GoGetty enables ambitious and highly qualified women, and soon also other diverse talents, as well as companies to find each other.
            .row.py-5.my-4
              .col-lg-6.my-auto
                .flex-display-column.content-column
                  h2 Use GoGetty to create a meaningful career of your dreams
                  .paragraph.mt-3
                    | Reap the benefits of the global D&I trend and choose between a rich pool of innovative companies in Denmark who have a strategic focus on diversity and inclusion.
              .col-lg-6
                .flex-display-img
                  = image_tag 'increased-charts.svg', class: 'my-4'
        .solutions-footer
          .container
            .row
              .col-lg-6
                == render "pages/solutions/for_companies_card"
              .col-lg-6
                == render "pages/solutions/for_partners_card"
        .col-lg-1
    == render "pages/solutions/solutions_content"    
    == render 'pages/solutions/more_info'