config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    Rails.application.routes.draw do
      root to: 'pages#show', id: 'talents'
      devise_for :users, controllers: {registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       confirmations: 'confirmations'}
      # get 'high_voltage/pages', to: 'high_voltage#pages'
      get '/pages/*id' => 'pages#show'
      get '/companies/:company_id/posts/:id', to: 'user_logged/posts#show', as: 'post'
      resources :after_signups, only: [:index]
      resources :subscriptions, only: %i[new create]
      get '/subscriptions/edit', to: 'subscriptions#edit', as: 'edit_subscription'
      get '/subscriptions/confirm', to: 'subscriptions#confirm', as: 'confirm_subscription_upgrade'
      put '/subscriptions/upgrade', to: 'subscriptions#update', as: 'update_subscription'
      resources :stripe_hooks, only: [:create]
      resources :mandrill_hooks, only: [:create]
      resources :partner_requests, only: [:create]
      resource :resend_confirmations, only: %i[new create]
      resources :tell_friends, only: [:create]
      resources :solutions, only: [:index]
      resources :company_searches, only: [:index]
      get '/create_company_searches', to: 'company_searches#create', as: 'get_create_company_searches'
      post '/create_company_searches', to: 'company_searches#create', as: 'post_create_company_searches'
      namespace :user_logged do
        get '/company_admins/:id', to: 'company_admins#create', as: 'become_admin'
        resources :company_nationalities, only: [:create, :update, :destroy]
        resources :company_languages, only: [:create, :update, :destroy]
        resources :company_profiles, only: [:update]
        resources :company_data, only: [:update]
        resource :companies, only: %i[new create edit update]
        resources :companies, only: [:show]
        resources :company_informations, only: [:update]
        resources :company_information_requests, only: [:create]
        resources :companies_diversity_policies, only: %i[create destroy]
        resources :text_policies, only: %i[create destroy]
        resources :goals_ways, only: %i[create destroy]
        resources :charges, only: %i[new create]
        resource :account_settings, only: %i[show edit update]
        resources :policy_requests, only: [:create]
        resources :policy_request_fields, only: [:create]
        resources :goal_requests, only: [:create]
        resources :diversity_requests, only: [:create]
        resources :company_requests, only: [:create]
        resources :coupons, only: [:create]
        resources :comments, only: %i[create destroy]
        resources :likes, only: [:create]
        resources :posts, only: %i[create update destroy]
        resources :follows, only: [:create]
        resource :walls, only: [:show]
        namespace :solutions do
          resource :axiom, only: [:show]
          resource :ontheagenda, only: [:show]
          resource :inspired_beyond_babies, only: [:show]
          resource :potential_company, only: [:show]
          resource :engaged_leadership, only: [:show]
          resource :introdus, only: [:show]
        end
        resources :solution_requests, only: [:create]
        namespace :account_settings do
          resources :billings, only: [:index]
          resources :upcoming_payments, only: [:index]
          resources :plans_users, only: %i[index destroy]
          resources :admin_invites, only: %i[index update]
          resources :notifications, only: %i[index update]
          resources :payment_credentials, only: [:edit, :new, :update, :create]
        end
        resource :company_settings, only: %i[show edit update]
        namespace :company_settings do
          resources :admins, only: %i[index update destroy]
          resources :admin_invites, only: %i[create update]
          resources :admin_requests, only: %i[update destroy]
          resources :info_requests, only: [:index]
          resources :diversity_requests, only: [:index]
          resources :goal_requests, only: [:index]
          resources :policy_requests, only: [:index]
          resources :followers_stats, only: [:index]
        end
        resource :platform_settings, only: [:show, :update]
        namespace :platform_settings do
          resources :users, only: %i[index show update destroy]
          resources :companies
          resources :requests, only: [:index]
          resources :plans, only: %i[index edit update]
          resources :employees_counts, except: [:show]
          resources :industries, except: [:show]
          resources :company_information_requests, only: [:index]
          resources :diversity_requests, only: [:index]
          resources :goal_requests, only: [:index]
          resources :policy_requests, only: [:index]
          resources :request_companies, only: [:create]
          resources :nationalities, except: [:show]
          resources :languages, except: [:show]
          resource :user_exports, only: [:show]
        end
      end
    end
  end
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  layout 'static'
  before_action :authenticate_user!, only: %i[create edit confirm update]

  def new
    redirect_to edit_subscription_path if current_user&.pro?
    @subscription = SubscriptionDecorator.decorate(Subscription.new)
    @subscription_form = ::Form::Subscription::Options.new
    @become_admin_company_id = params[:company_id]
  end

  def create
    result = ::Command::Subscription::Decide.new(decide_command_data).call
    if result.success?
      redirect_to result.data[:redirection_url], alert: result.data[:redirection_msg]
    else
      redirect_to new_subscription_path, alert: result.error.message
    end
  end

  def edit
    redirect_to new_subscription_path unless current_user&.pro?
    @subscription = SubscriptionDecorator.decorate(Subscription.new)
    @subscription_form = ::Form::Subscription::Upgrade.new
    @interval = current_user.current_subscription_interval
    @user_current_plan_name = current_user.current_subscription_plan.name
  end

  def confirm
    result = ::Command::Subscription::VerifyUpgrade.new(verify_upgrade_command_data).call
    if result.success? && result.data[:upgrade]
      plan_data_from_result(result)
      find_billing
      render 'confirm'
    else
      redirect_to edit_subscription_path, alert: result.error.message
    end
  end

  def update
    result = Command::Subscription::Update.new(current_user, subscription_upgrade_params).call
    if result.success?
      @plan_name = result.data.humanize.titleize
      render 'user_logged/charges/create'
    else
      redirect_to edit_subscription_path, alert: result.error.message
    end
  end

  private

  def decide_command_data
    [::Form::Subscription::Options.new(permitted_params.merge(commit: params[:commit])),
     session,
     current_user,
     params[:become_admin_company_id]]
  end

  def permitted_params
    params.require(:subscription).permit(:annual, :coupon)
  end

  def verify_upgrade_command_data
    [::Form::Subscription::Upgrade.new(permitted_params.merge(commit: params[:commit])),
     current_user,
     session]
  end

  def find_billing
    @billing = begin
                  Billing.find(session[:current_billing_id]).decorate
                rescue StandardError
                  nil
                end
  end

  def subscription_upgrade_params
    params.permit(:plan_name, :coupon)
  end

  def plan_data_from_result(result)
    @plan = result.data[:plan].decorate
    @plan_total_cost = @plan.total_cost(result.data[:interval])
    case result.data[:interval]
    when 'year'
      @plan_cost = @plan.annual_cost
      @plan_name = @plan.annual_stripe_name
    when 'month'
      @plan_cost = @plan.monthly_cost
      @plan_name = @plan.monthly_stripe_name
    end
  end
end

app/views/subscriptions/confirm.html.slim
.subscriptions.charges-new
  = form_tag update_subscription_path, method: :put do
    .subscriptions_header.subscriptions_header-confirm
      .container
        - if flash[:error].present?
          #error_explanation
            p= flash[:error]
        .row 
          .col.col-md-6.col-xs-12.col-sm-8.justify-content-center.mx-auto.py-5
            h1.pb-4= @plan_name.humanize.titleize
            .paragraph-small Your information is secure.
        .paragraph-small.coupon.mb-2 = @billing.coupon
        .row
          .mx-auto.pb-5.flex-header
            h1.mr-4= "#{@billing.payment_amount_to_charge} + #{@billing.plan.tax}% VAT (#{@billing.cost} total)"
    .subscriptions_body.subscriptions_body-confirm
      .container 
        .row.confirm-flex.my-4
          = hidden_field_tag(:plan_name, @plan_name)
          = hidden_field_tag(:coupon, @billing.object.coupon)
          = submit_tag 'Confirm', class:'btn btn-primary'
          br
          = link_to 'Cancel', edit_subscription_path
        .subscriptions_body-details.mt-5
          .subscriptions_body-details-tile.horizontal-border.horizontal-border-top
            .subscriptions_body-details-tile-item
              | View Company Profiles
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Follow Companies
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Like and comment on Companies posts
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Request Adding Companies
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Request more information on Companies Scores, Policies and Goals
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Diversity benchmarks by Industry, Country, Company size and Diversity Score
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Access Diversity Solution Providers
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Company Profile Administration
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Diversity score & dashboard
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.paid_plan_icon}")
          .subscriptions_body-details-tile.horizontal-border
            .subscriptions_body-details-tile-item
              | Ethnicity score & dashboard
              .new-label
                i.fa.fa-heart-o aria-hidden="true" 
                | NEW
            .subscriptions_body-details-tile-item
              i.fa(class="fa-#{@plan.inclusive_business_icon}")
    .subscriptions_footer
      .container
        .row.confirm-flex.my-4
          = submit_tag 'Confirm', class:'btn btn-primary'
          br
          = link_to 'Cancel', edit_subscription_path

app/views/subscriptions/edit.html.slim
.subscriptions
  = simple_form_for @subscription_form, url: confirm_subscription_upgrade_path, method: :get, html: {id: 'subscription_form'} do |f|
    .subscriptions_header
      .container
        .row
          .col.col-md-6.col-xs-12.col-sm-8.justify-content-center.mx-auto.py-5
            h1.pb-4 Subscriptions
            .paragraph-small Your information is secure.
        .row
          .mx-auto.pb-5
            = f.input :coupon, label: 'Discount code'
    .subscriptions_body
      .container
        .row.no-gutters
          .col-lg-4.subscriptions_body-card 
            .card-header.py-4
              h6 Basic
            div class=(@user_current_plan_name == 'business_basic' ? '' : 'strong-opacity')
              .card-subheader.py-4
                h1 FREE
                | &nbsp
              .card-body
                .card-body-item.py-4.px-5
                  - if @user_current_plan_name == 'business_basic'
                    .btn.btn-default.btn-primary.btn-block.disabled CURRENT PLAN
                  - else
                    .btn.btn-default.btn-primary.btn-block.disabled CAN'T DOWNGRADE
                .card-body-item
                  | Diversity score & dashboard
                  i.fa.fa-times aria-hidden="true"
                .card-body-item.card-flex
                  | Ethnicity score & dashboard
                  .new-label
                    i.fa.fa-heart-o aria-hidden="true"
                    | NEW
                  i.fa.fa-times aria-hidden="true"
                .card-body-item
                  | View Company Profiles
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Follow Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Like and comment on Companies posts
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request Adding Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request more information on Companies Scores, Policies and Goals
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Diversity benchmarks by Industry, Country, Company size and Diversity Score
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Access Diversity Solution Providers
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Company Profile Administration
                  i.fa.fa-times aria-hidden="true"
                .card-body-item.py-4.px-5
                  - if @user_current_plan_name == 'business_basic'
                    .btn.btn-default.btn-primary.btn-block.disabled CURRENT PLAN
                  - else
                    .btn.btn-default.btn-primary.btn-block.disabled CAN'T DOWNGRADE
          .col-lg-4.subscriptions_body-card 
            .card-header.py-4
              h6 Diverse Business
            div class=(@user_current_plan_name == 'inclusive_business' ? 'strong-opacity' : '')
              .card-subheader.py-4
                - if @interval == 'year'
                  h1= @subscription.diverse_business_annual
                  | per month (billed annually)
                - if @interval == 'month'
                  h1= @subscription.diverse_business_monthly
              .card-body
                .card-body-item.py-4.px-5
                  - if @user_current_plan_name == 'diverse_business'
                    .btn.btn-default.btn-primary.btn-block.disabled CURRENT PLAN
                  - elsif @user_current_plan_name == 'inclusive_business'
                    .btn.btn-default.btn-primary.btn-block.disabled CAN'T DOWNGRADE
                  - else
                    = button_tag :submit, name: 'commit', value: @subscription.diverse_business_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                      | BUY THIS PLAN
                .card-body-item
                  | Diversity score & dashboard
                  i.fa.fa-check aria-hidden="true"
                .card-body-item.card-flex
                  | Ethnicity score & dashboard
                  .new-label
                    i.fa.fa-heart-o aria-hidden="true"
                    | NEW
                  i.fa.fa-times aria-hidden="true"
                .card-body-item
                  | View Company Profiles
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Follow Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Like and comment on Companies posts
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request Adding Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request more information on Companies Scores, Policies and Goals
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Diversity benchmarks by Industry, Country, Company size and Diversity Score
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Access Diversity Solution Providers
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Company Profile Administration
                  i.fa.fa-check aria-hidden="true"
                .card-body-item.py-4.px-5
                  - if @user_current_plan_name == 'diverse_business'
                    .btn.btn-default.btn-primary.btn-block.disabled CURRENT PLAN
                  - elsif @user_current_plan_name == 'inclusive_business'
                    .btn.btn-default.btn-primary.btn-block.disabled CAN'T DOWNGRADE
                  - else
                    = button_tag :submit, name: 'commit', value: @subscription.diverse_business_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                      | BUY THIS PLAN
          .col-lg-4.subscriptions_body-card.mb-5 
            .card-header.py-4
              h6 Inclusive Business
            div class=(@user_current_plan_name == 'inclusive_business' ? 'strong-opacity' : '')
              .card-subheader.py-4
                - if @interval == 'year'
                  h1= @subscription.inclusive_business_annual
                  | per month (billed annually)
                - if @interval == 'month'
                  h1= @subscription.inclusive_business_monthly
              .card-body
                .card-body-item.py-4.px-5
                  - if @user_current_plan_name == 'inclusive_business'
                    .btn.btn-default.btn-primary.btn-block.disabled CURRENT PLAN
                  - else
                    = button_tag :submit, name: 'commit', value: @subscription.inclusive_business_commit, class: 'btn btn-default btn-primary btn-block' do
                      | BUY THIS PLAN
                .card-body-item
                  | Diversity score & dashboard
                  i.fa.fa-check aria-hidden="true"
                .card-body-item.card-flex
                  | Ethnicity score & dashboard
                  .new-label
                    i.fa.fa-heart-o aria-hidden="true"
                    | NEW
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | View Company Profiles
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Follow Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Like and comment on Companies posts
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request Adding Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request more information on Companies Scores, Policies and Goals
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Diversity benchmarks by Industry, Country, Company size and Diversity Score
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Access Diversity Solution Providers
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Company Profile Administration
                  i.fa.fa-check aria-hidden="true"
                .card-body-item.py-4.px-5
                  - if @user_current_plan_name == 'inclusive_business'
                    .btn.btn-default.btn-primary.btn-block.disabled CURRENT PLAN
                  - else
                    = button_tag :submit, name: 'commit', value: @subscription.inclusive_business_commit, class: 'btn btn-default btn-primary btn-block' do
                      | BUY THIS PLAN

app/views/subscriptions/new.html.slim
.subscriptions
  = simple_form_for @subscription_form, url: subscriptions_path, method: :post, html: {id: 'subscription_form'} do |f|
    = hidden_field_tag(:become_admin_company_id, @become_admin_company_id)
    .subscriptions_header
      .container
        .row
          .col.col-md-6.col-xs-12.col-sm-8.justify-content-center.mx-auto.py-5
            h1.pb-4 Subscriptions
            .paragraph-small Your information is secure.
        .row
          .mx-auto.pb-5
            = f.input :coupon, label: 'Discount code'
            = f.check_box :annual, label: 'Yearly', checked: true, hidden: true
            - if current_user.monthly_billing_permission
              .switch-button
                button.btn.btn-toggle.active#switch-button aria-pressed="true" autocomplete="off" data-toggle="button" type="button"
                  .handle  
    .subscriptions_body
      .container
        .row.no-gutters
          .col-lg-4.subscriptions_body-card
            .card-header.py-4
              h6 Basic
            div.strong-opacity
              .card-subheader.py-4
                h1 FREE
                | &nbsp
              .card-body
                .card-body-item.py-4.px-5
                  = button_tag :submit, name: 'commit', value: @subscription.business_basic_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                    'YOUR CURRENT PLAN
                .card-body-item
                  | Diversity score & dashboard
                  i.fa.fa-times aria-hidden="true"
                .card-body-item.card-flex
                  | Ethnicity score & dashboard
                  .new-label
                    i.fa.fa-heart-o aria-hidden="true"
                    | NEW
                  i.fa.fa-times aria-hidden="true"
                .card-body-item
                  | View Company Profiles
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Follow Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Like and comment on Companies posts
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request Adding Companies
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Request more information on Companies Scores, Policies and Goals
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Diversity benchmarks by Industry, Country, Company size and Diversity Score
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Access Diversity Solution Providers
                  i.fa.fa-check aria-hidden="true"
                .card-body-item
                  | Company Profile Administration
                  i.fa.fa-times aria-hidden="true"
                .card-body-item.py-4.px-5
                  = button_tag :submit, name: 'commit', value: @subscription.business_basic_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                    'YOUR CURRENT PLAN
          .col-lg-4.subscriptions_body-card
            .card-header.py-4
              h6 Diverse Business
            .card-subheader.py-4
              .annual_cost
                h1= @subscription.diverse_business_annual
                | per month (billed annually)
              h1.monthly_cost style="display:none"
                = @subscription.diverse_business_monthly
            .card-body
              .card-body-item.py-4.px-5
                = button_tag :submit, name: 'commit', value: @subscription.diverse_business_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                  | BUY THIS PLAN
              .card-body-item
                | Diversity score & dashboard
                i.fa.fa-check aria-hidden="true"
              .card-body-item.card-flex
                | Ethnicity score & dashboard
                .new-label
                  i.fa.fa-heart-o aria-hidden="true"
                  | NEW
                i.fa.fa-times aria-hidden="true"
              .card-body-item
                | View Company Profiles
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Follow Companies
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Like and comment on Companies posts
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Request Adding Companies
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Request more information on Companies Scores, Policies and Goals
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Diversity benchmarks by Industry, Country, Company size and Diversity Score
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Access Diversity Solution Providers
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Company Profile Administration
                i.fa.fa-check aria-hidden="true"
              .card-body-item.py-4.px-5
                = button_tag :submit, name: 'commit', value: @subscription.diverse_business_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                  | BUY THIS PLAN
          .col-lg-4.subscriptions_body-card.mb-5
            .card-header.py-4
              h6 Inclusive Business
            .card-subheader.py-4
              .annual_cost
                h1= @subscription.inclusive_business_annual
                | per month (billed annually)
              h1.monthly_cost style='display:none'
                = @subscription.inclusive_business_monthly
            .card-body
              .card-body-item.py-4.px-5
                = button_tag :submit, name: 'commit', value: @subscription.inclusive_business_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                  | BUY THIS PLAN
              .card-body-item
                | Diversity score & dashboard
                i.fa.fa-check aria-hidden="true"
              .card-body-item.card-flex
                | Ethnicity score & dashboard
                .new-label
                  i.fa.fa-heart-o aria-hidden="true"
                  | NEW
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | View Company Profiles
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Follow Companies
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Like and comment on Companies posts
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Request Adding Companies
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Request more information on Companies Scores, Policies and Goals
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Diversity benchmarks by Industry, Country, Company size and Diversity Score
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Access Diversity Solution Providers
                i.fa.fa-check aria-hidden="true"
              .card-body-item
                | Company Profile Administration
                i.fa.fa-check aria-hidden="true"
              .card-body-item.py-4.px-5
                = button_tag :submit, name: 'commit', value: @subscription.inclusive_business_commit, class: 'btn btn-default btn-primary btn-block btn-transparent' do
                  | BUY THIS PLAN